// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGRAKDQuPw-J8vysTZGBmRPnGGoYzVOkw',
    appId: '1:988696097583:web:f454f474d9e3795b2b67da',
    messagingSenderId: '988696097583',
    projectId: 'qismat-flutter-app',
    authDomain: 'qismat-flutter-app.firebaseapp.com',
    storageBucket: 'qismat-flutter-app.appspot.com',
    measurementId: 'G-DYSGTWFRPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0lDAJ6fDmWKtSC83ax4bv7egT1RFTpm4',
    appId: '1:988696097583:android:f53965151fd982512b67da',
    messagingSenderId: '988696097583',
    projectId: 'qismat-flutter-app',
    storageBucket: 'qismat-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrewPNzldNZVVilvWuoDv51iiO08gSfbs',
    appId: '1:988696097583:ios:d9516e98e3b277c52b67da',
    messagingSenderId: '988696097583',
    projectId: 'qismat-flutter-app',
    storageBucket: 'qismat-flutter-app.appspot.com',
    iosBundleId: 'com.example.qismat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrewPNzldNZVVilvWuoDv51iiO08gSfbs',
    appId: '1:988696097583:ios:105927b6a21b48472b67da',
    messagingSenderId: '988696097583',
    projectId: 'qismat-flutter-app',
    storageBucket: 'qismat-flutter-app.appspot.com',
    iosBundleId: 'com.example.qismat.RunnerTests',
  );
}
